name: Hibachi

# The package version.  See the Haskell package versioning policy (PVP)
# for standards guiding when and how versions should be incremented.
# https://wiki.haskell.org/Package_versioning_policy
# PVP summary:      +-+------- breaking API changes
#                   | | +----- non-breaking API additions
#                   | | | +--- code changes with no API change
version:            0.1.0.0

synopsis:           A Blog Engine
homepage:           https://dequbed.space/

license:            GPL-3
license-file:       LICENSE

author:             Gregor Reitzenstein
maintainer:         me@dequbed.space

category:           Web

extra-source-files: 
  - README.md
  - CHANGELOG.md

library:
  source-dirs: src
  dependencies:
    - base           >=4.12 && <4.13
    - clay           >=0.13 && <0.14
    - cmark          >=0.6  && <0.7
    - gitlib         >=3.1  && <3.2
    - gitlib-libgit2 >=3.1  && <3.2
    - lens           >=4    && <5
    - lucid          >=2.9  && <2.10
    - shake          >=0.18 && <0.19
    - skylighting    >=0.8  && <0.9
    - text           >=1.2  && <1.3

executables:
  hibachi:
    main: Main.hs
    source-dirs: app
    dependencies:
      - Hibachi

# vim: nospell
